const carta = [
    {
        id : 1,
        name : 'Muzzarella',
        description : 'Sólo para expertos',
        prize : 900,
        img : './assets/comida-img/muzza.jpg',
        category : 'pizzas',
    } ,
    {
        id : 2,
        name : 'Napolitana',
        description : 'La favorita de D10S',
        prize : 1200,
        img : './assets/comida-img/napolitana.jpg',
        category : 'pizzas',
    } ,
    {
        id : 3,
        name : 'Fugazzeta',
        description : '¡Con extra cebolla!',
        prize : 1100,
        img : './assets/comida-img/fugazzeta.jpg',
        category : 'pizzas',
    } ,
    {
        id : 4,
        name : '4 Quesos',
        description : 'La favorita de John Lennon',
        prize : 1400,
        img : './assets/comida-img/4quesos.jpg',
        category : 'pizzas',
    } ,
    {
        id : 5,
        name : 'Veggie',
        description : '¡Hasta parece deliciosa eh!',
        prize : 1430,
        img : './assets/comida-img/veggie.jpg',
        category : 'pizzas',
    } ,
    {
        id : 6,
        name : 'Doble Cheddar',
        description : 'Para más placer',
        prize : 800,
        img : './assets/comida-img/doble_cheddar.jpg',
        category : 'hamburguesas',
    } ,
    {
        id : 7,
        name : 'Triple Bacon',
        description : 'Sólo para estómagos valientes',
        prize : 1100,
        img : './assets/comida-img/triple_bacon.jpg',
        category : 'hamburguesas',
    } ,
    {
        id : 8,
        name : 'Jamón Serrano',
        description : 'El verdadero jamón Serrano',
        prize : 900,
        img : './assets/comida-img/jamon_serrano.jpg',
        category : 'hamburguesas',
    } ,
    {
        id : 9,
        name : 'Papas Fritas',
        description : 'Mirá lo que son esas papas',
        prize : 700,
        img : './assets/comida-img/papas.jpg',
        category : 'napapuki',
    } ,
    {
        id : 10,
        name : 'Super Cheddar',
        description : 'Para devorarlas',
        prize : 900,
        img : './assets/comida-img/papas_cheddar.png',
        category : 'napapuki',
    } ,
    {
        id : 11,
        name : 'Vegetariano',
        description : 'La mejor opción',
        prize : 600,
        img : './assets/comida-img/burrito_veggie.jpg',
        category : 'wraps',
    } ,
    {
        id : 12,
        name : 'Chicken Wrap',
        description : '¡Nunca falla!',
        prize : 800,
        img : './assets/comida-img/chicken_wrap.jpg',
        category : 'wraps',
    } ,
    {
        id : 13,
        name : 'Tacos',
        description : 'Como si estuvieras en México',
        prize : 1200,
        img : './assets/comida-img/tacos.jpg',
        category : 'mexican-food',
    } ,
    {
        id : 14,
        name : 'Nachos',
        description : 'Nacho nacho meeen...',
        prize : 900,
        img : './assets/comida-img/nachos.jpg',
        category : 'mexican-food',
    } ,
    {
        id : 15,
        name : 'Batido de chocolate',
        description : 'Pecado hecho bebida',
        prize : 600,
        img : './assets/comida-img/batido_chocolate.jpg',
        category : 'batidos',
    } ,
    {
        id : 16,
        name : 'Batido de frutilla',
        description : 'La vieja confiable',
        prize : 600,
        img : './assets/comida-img/batido_frutilla.jpg',
        category : 'batidos',
    } ,

];